### ISSUE TITLE
渲染时，无法得到根目录下子目录中的文件并且无法渲染html后缀文件

### ISSUE THREAD

**Issue by 2300206764** [aui/art-template#449]
问题1：无法得到根目录下子目录中的文件
目录结构
```
—views
  ┴auth.art
```
调用代码
```
app.set('view options', {
    rule: rule,
    root: process.cwd() + '/views/',
    debug: true,
});

res.render('auth', {title: '测试标题'});
```
但是如果目录结构改变一下
```
—views
  ┴layout
      ┴auth.art
```
调用代码
```
app.set('view options', {
    rule: rule,
    root: process.cwd() + '/views/',
    debug: true,
});

res.render('layout/auth', {title: '测试标题'});
res.render('/layout/auth', {title: '测试标题'});
res.render('layout.auth', {title: '测试标题'});
//三者均无法使用，前两者错误均为
Failed to lookup view "layout/auth" in views directory "/root/views"
    at Function.render (/root/node_modules/express/lib/application.js:580:17)
    at ServerResponse.render (/root/node_modules/express/lib/response.js:971:7)
    at /root/core/http/route.js:51:9
//第三者错误为
Error: Cannot find module 'auth'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at new View (/root/node_modules/express/lib/view.js:80:30)
```

问题2：无法渲染html后缀文件
调用代码
```
app.set('view options', {
    rule: rule,
    root: process.cwd() + '/views/',
    debug: true,
    extname: '.html'
});

res.render('auth', {title: '测试标题'});
//不管html文件在哪个目录，总之就是无法指定html后缀，如果加上html后缀就会有下面报错
//如果不加后缀，那么会报错找不到auth 文件，根据错误分析应该是没有自动添加后缀
```
错误为
```
Cannot find module 'html'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
```

**Comment by aui** [comment]
最好能够提供一个可以直接运行的演示，我需要调试

**Comment by 2300206764** [comment]
[Github-art.zip](https://github.com/aui/art-template/files/1167099/Github-art.zip)
这里面是有对应了3种情况的文件，对应端口为8081,8082,8083

**Comment by 2300206764** [comment]
如果可以，我推荐使用点语法来表示目录，既美观又大方

**Comment by Janking** [comment]
@2300206764 运行了一下你的代码，

问题一，没还原出你的情况

```
const express = require('express');
/* @var */
const app = express();
const template = require('art-template');
app.engine('art', require('express-art-template'));
app.set('view engine', 'art');
let rule = template.defaults.rules.unshift({
  test: /@([\w\W]*?)}}/,
  use: function (match, code) {
    return { output: 'raw', code: JSON.stringify(code + '}}') }
  }
});

app.set('view options', {
  rule: rule,
  root: process.cwd() + '/views/',
  debug: true
});

app.get('/', function (req, res) {
  // 改动地方，运行后是能渲染到 layout/auth.art 文件的
  res.render('layout/auth', { title: '测试标题' });
});

app.get('/test', function (req, res) {
  res.render('auth2', { title: '测试标题' });
});

const server = app.listen(8081, function () {
  console.log("http server open success")
});
```

**Comment by Janking** [comment]
@2300206764 
问题二：

```
const express = require('express');
/* @var */
const app = express();
const template = require('art-template');
// 修改位置 1 ： 设置express 渲染模板后缀为 html  ，并以 `html`为键存储 require('express-art-template')
app.engine('html', require('express-art-template')); 
// 修改位置 2：选择模板引擎名称 => `html`
app.set('view engine', 'html')
let rule = template.defaults.rules.unshift({
  test: /@([\w\W]*?)}}/,
  use: function (match, code) {
    return { output: 'raw', code: JSON.stringify(code + '}}') }
  }
});

app.set('view options', {
  rule: rule,
  root: process.cwd() + '/views/',
  debug: true
});

app.get('/', function (req, res) {
  res.render('layout/auth', { title: '测试标题' });
});

app.get('/test', function (req, res) {
  res.render('auth2', { title: '测试标题' });
});

const server = app.listen(8081, function () {
  console.log("http server open success")
});
```

**Comment by 2300206764** [comment]
@Janking 问题一可能在于我的node版本过高，我的版本是8.1.4，请重新测试。
问题二，这是一种解决办法，但是官方提供的extname的问题是不需要解决了吗？

**Comment by Janking** [comment]
@2300206764 我是在8.1.3的版本下运行的，刚update到8.2.1，确实出现你说的问题，我尝试debug一下。
问题二：我不太理解作者提供extname的意图，因为我源码还没看完，这个让 @aui 糖饼解释一下吧。

**Comment by 2300206764** [comment]
@Janking 好的，幸苦你了

**Comment by Janking** [comment]
@2300206764 
我现在是在 8.2.1的版本运行你的 main3.js 文件
  // 原本代码 res.render('/layout/auth', { title: '测试标题' });
  // 修改后    res.render('layout/auth', { title: '测试标题' });

原因是： express在寻找目标模板文件的时候，是通过path.resolve()来处理的，你原来的 `/layout/auth` 之所以出错，是因为 `path.resolve('/views','/layout')` 出错了。
resolve的用法请查看 [http://javascript.ruanyifeng.com/nodejs/path.html#toc1](http://javascript.ruanyifeng.com/nodejs/path.html#toc1)

```
const express = require('express');
/* @var */
const app = express();
const template = require('art-template');
app.engine('art', require('express-art-template'));
app.set('view engine', 'art');
let rule = template.defaults.rules.unshift({
  test: /@([\w\W]*?)}}/,
  use: function (match, code) {
    return { output: 'raw', code: JSON.stringify(code + '}}') }
  }
});

app.set('view options', {
  rule: rule,
  root: process.cwd() + '/views/',
  debug: true
});

app.get('/', function (req, res) {
  // 原本代码 res.render('/layout/auth', { title: '测试标题' });
  // 修改后    res.render('layout/auth', { title: '测试标题' });
  res.render('layout/auth', { title: '测试标题' });
});


const server = app.listen(8083, function () {
  console.log("http server open success")
});


```

**Comment by 2300206764** [comment]
@Janking 嗯，那路径问题应该是解决了。麻烦能解决一下extname的问题吗

**Comment by Janking** [comment]
@2300206764 我对express3的源码不熟悉，但是在express4里头，对extname的识别原理是这样的：

1.  express实例中有一个`engines`对象，用来存储各种模板引擎，当你这样写`  app.engine('art', require('express-art-template'));`的时候，express会往engines对象存入一个名为art的模板引擎，结果大概如下：
```
this.engines = {
  'art' : require('express-art-template'))
}
```
2.  `app.set('view engine', 'art')` 是选择默认引擎为 `art`，即：this.defaultEngine = 'art'

3. 在你调用`render('layout/auth'，{title:'xxxx'})`，目标文件URL的拼接为path.resolve('/views','layout/auth'+'.'+this.defaultEngine)。
目标模板的URL拼接结果为：`/views/layout/auth.art`

4. 所以，你要渲染什么后缀格式的文件，只要把上面的两个art替换为你想要的文件后缀即可

从而我并没有发现art-template的extname有什么作用？个人猜测是在express3的时候有效吧？我没去验证。

**Comment by 2300206764** [comment]
@Janking 问题就出在这里，如果你直接写出后缀，就会出现问题2的情况

**Comment by Janking** [comment]
@2300206764 express去识别extname都是要去engines中拿相应的模板引擎，如果你需要同时支持art和html的模板，建议你这样写
```
app.engine('art', require('express-art-template'));
app.engine('html', require('express-art-template'));
```
这样你就可以这样去渲染html模板了

```
app.get('/test', function (req, res) {
  res.render('auth2.html', { title: '测试标题' });
});

```

不过我这强迫症很不喜欢一个项目，多个不同格式的模板，哈哈哈

**Comment by 2300206764** [comment]
@Janking 额。。art template的extname稍微有些不同，作者说指定extname后会在没有后缀的路径下自动添加，主要问题是他无法自动添加。

**Comment by Janking** [comment]
哈哈，这个就得作者给出个说明解释了，我还没办法看完他这个的源码，这个开源项目就糖饼一个人维护，也是不易 @2300206764

**Comment by aui** [comment]
art-template 是一个独立的模板引擎，`extname` 的配置作用：如果要渲染的模板路径没有后缀名，则会自动添加 extname —— 这和 nodejs `require()` 行为很像，可以省去 `js` 后缀名。[路径处理代码](https://github.com/aui/art-template/blob/master/lib/compile/adapter/resolve-filename.js#L29)

art-template 的 `extname` 默认值为 `"art"`。

**Comment by 2300206764** [comment]
好吧。。
