### ISSUE TITLE
Can't use res.locals in express middleware

### ISSUE THREAD

**Issue by wenkanglin** [aui/art-template#459]
### bug repo
https://github.com/wenkanglin/express-app

### package version
* art-template: 4.12.1
* node: 8.0.0
* npm: 5.0.0
* express: 4.15.2

### bug复现
```
git clone https://github.com/wenkanglin/express-app.git
yarn install
```
浏览器访问`localhost:3000`，出现报错信息如下：
```
TypeError: target.hasOwnProperty is not a function
    at extend (E:\projects\express-app\node_modules\art-template\lib\compile\adapter\extend.js:30:24)
    at extend (E:\projects\express-app\node_modules\art-template\lib\compile\adapter\extend.js:31:33)
    at Object.Defaults.$extend (E:\projects\express-app\node_modules\art-template\lib\compile\defaults.js:91:16)
    at View.renderFile [as engine] (E:\projects\express-app\node_modules\express-art-template\src\index.js:26:35)
    at View.render (E:\projects\express-app\node_modules\express\lib\view.js:128:8)
    at tryRender (E:\projects\express-app\node_modules\express\lib\application.js:640:10)
    at Function.render (E:\projects\express-app\node_modules\express\lib\application.js:592:3)
    at ServerResponse.render (E:\projects\express-app\node_modules\express\lib\response.js:971:7)
    at E:\projects\express-app\app.js:48:7
    at Layer.handle_error (E:\projects\express-app\node_modules\express\lib\router\layer.js:71:5)
```

在`routes/index.js`中，注释掉这一行：
```
res.locals.message = 'hello express';
```
报错信息就会消失，正常运行

### bug原因
在`art-template/lib/compile/adapter/extend.js`源文件中，第27行代码：
```
if (target.hasOwnProperty(index))
```
这里出现情况：`target.hasOwnProperty`方法不存在。麻烦 @aui 帮忙修复一下，谢谢 。

**Comment by mingjiu** [comment]
哎呀，我入坑了。

**Comment by ugrg** [comment]
貌似跟我发现的那个是一个问题,

**Comment by mingjiu** [comment]
@ugrg 你有什么解决办法吗？

**Comment by ugrg** [comment]
上周我在github上提了BUG了,貌似他们已经更新这个问题了.你可以更新一下代码试试,如果还不对,你可以尝试把以下代码手动修改一下:
```js
//node_modules/art-template/lib/compile/adapter/extend.js
        for (var index in target)
        {
            if (target.hasOwnProperty(index))
            {
                object[index] = extend(target[index], object[index]);
            }
        }
//修改为
        for (var index in target)
        {
            if (Object.prototype.hasOwnProperty.call(target, index))
            {
                object[index] = extend(target[index], object[index]);
            }
        }
```

**Comment by wenkanglin** [comment]
npm上是更新了`patch`版本到`4.12.2`，github release还是`4.12.1`版本，不知道是不是解决了问题

**Comment by mingjiu** [comment]
的确是可以了。感谢作者
